name: PR automerge

# Important notes:
#
# Automatic deletion of PR branches after merge is done through GitHub repository settings
# https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches
#
# "Require branches to be up to date before merging" is also enabled for the repository
#
# "check_suite" and "check_run" are not triggered for the GitHub Actions to prevent recusivity. More information
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#check_suite
# To bypass this the codecov status reporting is used. It will be reported at the end of `ci` workflow and trigger
# automerge workflow.

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest

    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge,!do NOT merge,!invalid,!wontfix"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "0" # Preventing retry mechanism
          MERGE_RETRY_SLEEP: "0"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_METHOD: "rebase"
